name: chessboard_js
description: A chessboard widget to use with chessjs. Use chessjs for the logic of the game, and this package to display the game.
version: 0.0.2+7
homepage: https://github.com/chessasuke/chessboard_js
#publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  chessjs: ^0.0.1+6
  tuple: ^2.0.0
  equatable: ^2.0.3
  audioplayers: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/chessboard_js/images/brown_board.png
    - packages/chessboard_js/images/dark_brown_board.png
    - packages/chessboard_js/images/green_board.png
    - packages/chessboard_js/images/orange_board.png
    - packages/chessboard_js/assets/chess_move.mp3

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
